## Functional Programming in Python

In [1]:
import numpy as np

a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


### `map`

In [2]:
def special_function(x):
    return 1 + x**2

a_map = map(special_function,list(a))
print(special_function(1))
print(list(a_map))

2
[1, 2, 5, 10, 17, 26, 37, 50, 65, 82]


We can also use an anonymous function `lambda` to save us having to define the function explicitely:

In [3]:
f = lambda x: x**3
f(2)

8

In [4]:
a_map_l = map(lambda x: 1 + x**2, list(a))
print(list(a_map_l))

[1, 2, 5, 10, 17, 26, 37, 50, 65, 82]


## List Comprehensions

Actually you don't need to use `map`:

In [5]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
print([special_function(thing) for thing in a])

[1, 2, 5, 10, 17, 26, 37, 50, 65, 82]


In [7]:
a_prime = np.array([special_function(thing) for thing in a])
print(a_prime)
print(type(a_prime))

[ 1  2  5 10 17 26 37 50 65 82]
<class 'numpy.ndarray'>


In [8]:
squares = [x**2 for x in np.arange(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


### `filter`

In [9]:
a_filter = filter(lambda x: x < 2,list(a))
print(list(a_filter))

[0, 1]


### `reduce`

In [10]:
from functools import reduce
a_reduce = reduce((lambda x, y: x+2*y), list(a))
print(a_reduce)

90


## Applying functions to `numpy` arrays

In [11]:
a_np = np.array(a)
print(a_np)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
sf_vectorized = np.vectorize(special_function)
a_np_prime = sf_vectorized(a_np)
print(a_np_prime)

[ 1  2  5 10 17 26 37 50 65 82]


In [ ]:
a_np_loop = np.zeros_like(a_np)
for i in range(len(a_np)):
    a_np_loop[i] = special_function(a_np[i])
print(a_np_loop)

### Exercises!

1. Make an anonymous function (use `lambda`) that raises its input to the power 4 and check that it works
2. Print all the numbers between 1 and 100 that are divisible by 3 or 5 using a list comprehension.
3. Use `filter` to print all the even numbers between 0 and 20.
4. Write a function that uses `reduce`.  What could you do?