## Functional Programming in Python

In [1]:
import numpy as np

a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


### `map`

In [2]:
def special_function(x):
    return 1 + x**2

a_map = map(special_function,list(a))
print(special_function(1))
print(list(a_map))

2
[1, 2, 5, 10, 17, 26, 37, 50, 65, 82]


We can also use an anonymous function `lambda` to save us having to define the function explicitely:

In [ ]:
def f(x):
    return x**3

In [3]:
f =  lambda x: x**3
print(type(f))
f(2)

<class 'function'>


8

In [4]:
a_map_l = map(lambda x: 1 + x**2, list(a))
print(list(a_map_l))

[1, 2, 5, 10, 17, 26, 37, 50, 65, 82]


## List Comprehensions

Actually you don't need to use `map`:

In [5]:
a_prime = np.array([special_function(thing) for thing in a])
print(a_prime)
print(type(a_prime))

[ 1  2  5 10 17 26 37 50 65 82]
<class 'numpy.ndarray'>


In [6]:
squares = [x**2 for x in np.arange(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


### `filter`

In [7]:
a_filter = filter(lambda x: x < 2,list(a))
print(list(a_filter))

[0, 1]


### `reduce`

In [15]:
from functools import reduce
print(np.arange(3))
a_reduce = reduce((lambda x, y: x+2*y), np.arange(3))
print(a_reduce)

[0 1 2]
6


(0 + 2*1) = x
2 + 2*2 = 6

## Applying functions to `numpy` arrays

In [16]:
a_np = np.array(a)
print(a_np)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
%%time
sf_vectorized = np.vectorize(special_function)
a_np_prime = sf_vectorized(a_np)
print(a_np_prime)

[ 1  2  5 10 17 26 37 50 65 82]
CPU times: user 2.72 ms, sys: 2.19 ms, total: 4.91 ms
Wall time: 52.1 ms


In [18]:
%%time
a_np_loop = np.zeros_like(a_np)
for i in range(len(a_np)):
    a_np_loop[i] = special_function(a_np[i])
print(a_np_loop)

[ 1  2  5 10 17 26 37 50 65 82]
CPU times: user 2.09 ms, sys: 2.17 ms, total: 4.27 ms
Wall time: 92.5 ms
