In [10]:
import numpy as np

In [11]:
x = np.arange(1,101)
y = np.ones((3,3))
z = np.full(y.shape,"tjena")
print(z)

[['tjena' 'tjena' 'tjena']
 ['tjena' 'tjena' 'tjena']
 ['tjena' 'tjena' 'tjena']]


In [12]:
words = "This sentence is false.  This one too.".replace("."," ").split()
print(words)

['This', 'sentence', 'is', 'false', 'This', 'one', 'too']


In [17]:
v1 = np.ones(5)
v2 = v1; v3 = v1; v4 = v1;
v = np.vstack((v1,v2,v3,v4))
print(v)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [14]:
words_np = np.array(words)
print(set(words))
print(len(set(words)))

{'is', 'too', 'sentence', 'one', 'false', 'This'}
6


In [18]:
three_five = [x for x in np.arange(100) if x%3 == 0 or x%5 == 0]
print(three_five)

[0, 3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99]
